### PR TITLE
Add static content for lab Bielefeld

### PR DESCRIPTION
**Pull request by gllrt**
For the lab in Bielefeld the location got added to respective csv, markdown down with description and hexagon logo were created.

### CODE REVIEW

**Comment by calculatinginfinity** [comment]
> For the lab in Bielefeld the location got added to respective csv, markdown down with description and hexagon logo were created.

Please amend:

1. Headline "Code For Bielefeld" -> "Code for Bielefeld"
2. Marker in map "bielefeld" -> "Bielefeld"
3. Please add a gettogether link

Thanks

**Comment by gllrt** [comment]
@calculatinginfinity done, thanks for the hints

**Comment by ubergesundheit** [comment]
Hey @gllrt could you update your branch to be in sync with `dev` ? Or check the `Allow edits from maintainers` checkbox. Thanks :)

**Comment by gllrt** [comment]
@ubergesundheit synced 'our' branch right now. As the pull requesting repo is not a personal one but belongs to our lab's organisation account, the `Allow edits from maintainers` checkbox seems to be missing

**Comment by ubergesundheit** [comment]
Thanks!

**Pull request merged**
